CREATE TABLE naver_shopping_products (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
keyword VARCHAR(50) NOT NULL,
product_name VARCHAR(255) NOT NULL,
price INT NOT NULL,
link VARCHAR(500) NOT NULL UNIQUE,
mall_name VARCHAR(100),
crawled_at DATETIME DEFAULT CURRENT_TIMESTAMP
);